### ISSUE TITLE
Errors on loading dataset "MNIST.pkl, CIFAR10.pkl and ZINC.pkl" using pickle.load() in superpixels.py

### ISSUE THREAD

**Issue by wdimmy** [lukecavabarrett/pna#9]
File "/Users/dimmy/miniconda3/lib/python3.8/site-packages/dgl/graph_index.py", line 53, in __setstate__
    num_nodes, readonly, src, dst = state
ValueError: too many values to unpack (expected 4)

**Comment by gcorso** [comment]
Hi, those files regarding the "Benchmarking GNNs" datasets were imported from the [paper's repository](https://github.com/graphdeeplearning/benchmarking-gnns). The problem lies in an update to the DGL library that changed the loading of its datasets therefore your options are to use an older version of DGL or update the file based on the updated version of the [Benchmarking GNN repo](https://github.com/graphdeeplearning/benchmarking-gnns).
Let me know if you still have issues.

**Comment by wdimmy** [comment]
Hi, thanks for your reply. DGL 0.3 is workable but it can not be compatible with  python 3.8.  I tried Python 3.6 with DGL 0.3,  and now it works.

**Comment by gcorso** [comment]
I think that the latest working version is dgl==0.4.2 and for some reason there was a breaking change with the version 0.4.3 (see this issue https://github.com/dmlc/dgl/issues/1494 I raised with dgl and the connected ones).
